from enum import Enum

class Role(Enum):
    OWNER = "OWNER"
    MANAGER = "MANAGER"
    SPECIALIST = "SPECIALIST"
    EMPLOYEE = "EMPLOYEE"

class State(Enum):
    NEW = 'NEW'
    CONFIRMED = 'CONFIRMED'
    IN_PROGRESS = 'IN_PROGRESS'
    WAITING_EXTERNAL = 'WAITING_EXTERNAL'
    RESOLVED = 'RESOLVED'
    CLOSED = 'CLOSED'
    CANCELLED = 'CANCELLED'

class Priority(Enum):
    CRITICAL = 'CRITICAL'
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = 'LOW'

class Depart(Enum):
    HR = 'HR'
    SECURITY = 'SECURITY'
    ACCOUNTANT= 'ACCOUNTANT'
    ARS = 'ARS'
    IT = 'IT'
    INVENTORY = 'INVENTORY'
    STORE = 'STORE'
    MARKETING = 'MARKETING'
    SERVICE = 'SERVICE'
    TOP_MANAGEMENT = 'TOP_MANAGEMENT'

class ClassAlerts(Enum):
    CRITICAL_ALERTS = 'CRITICAL_ALERTS'
    SECURITY_ALERTS = 'SECURITY_ALERTS'
    HR_ALERTS = 'HR_ALERTS'
    CASH_ALERTS = 'CASH_ALERTS'
    SERVICE_ALERTS = 'SERVICE_ALERTS'