CRITICAL_ALERTS:
  list:
    - NO_ELECTRICITY
    - FULL_NO_WATER
    - NO_INTERNET
    - GOVERNMENT_INSPECTION
    - NOT_WATER
  target:
    TOP_MANAGEMENT

SECURITY_ALERTS:
  list:
    -THEFTS_ALERT
    -AGGRESSIONS_ALERT
    -ALARM_ALERT
    -LOST_KEY_ALERT
  target:
    SECURITY

HR_ALERTS:
  list:
     - STAFF_SHORTAGES
     - INTERN_DID_NOT_SHOW_UP
     - SCHEDULING_ISSUES
     - TEAM_CONFLICT
  target:
    HR

CASH_ALERTS:
  list:
    - RETURNS
    - REPORTING_ERRORS
    - CASH_DISCREPANCIES
  target:
    ACCOUNTANT

SERVICE_ALERTS:
  list:
  - CUSTOMER_COMPLAINTS
  - CONFLICT
  - CONTACT
  target:
    SERVICE