CRITICAL_ALERTS:
  NO_ELECTRICITY:
    class: CRIT_ALERT
  FULL_NO_WATER:
    class: CRIT_ALERT
  NO_INTERNET:
    class: CRIT_ALERT
  GOVERNMENT_INSPECTION:
    class: CRIT_ALERT
  NO_COLD_OR_HOT_WATER:
    class: HIGH_ALERT

SECURITY_ALERTS:
  THEFTS_ALERT:
    class: SEC_ALERT
  AGGRESSIONS_ALERT:
    class: SEC_ALERT
  ALARM_ALERT:
    class: SEC_ALERT
  LOST_KEY_ALERT:
    class: SEC_ALERT

HR_ALERTS:
   STAFF_SHORTAGES:
     class: HR_ALERT
   INTERN_DID_NOT_SHOW_UP:
     class: HR_ALERT
   SCHEDULING_ISSUES:
     class: HR_ALERT
   TEAM_CONFLICT:
     class: HR_ALERT

CASH_ALERTS:
  RETURNS:
    class: CASH_ALERT
  REPORTING_ERRORS:
    class: CASH_ALERT
  CASH_DISCREPANCIES:
    class: CASH_ALERT

SERVICE_ALERTS:
  CUSTOMER_COMPLAINTS:
    class: SERVICE_ALERT
  CONFLICT:
    class: SERVICE_ALERT
  CONTACT:
    class: SERVICE_ALERT