STORE_REQUEST:
  BAR_FRESH:
    class: SUPPLY_REGULAR
  BAR_CONSUMABLES:
    class: SUPPLY_REGULAR
  BAR_DRINKS_AND_COFFEE:
    class: SUPPLY_REGULAR
  BAR_NOT_MILK_FAST:
    class: SUPPLY_CRITICAL
  BAR_NOT_COFFEE_FAST:
    class: SUPPLY_CRITICAL
  SALES_CONSUMABLES:
    class: SUPPLY_REGULAR
  SALES_CHEMICAL:
    class: SUPPLY_REGULAR
  SALES_HOUSE_GOODS:
    class: SUPPLY_REGULAR
  SALES_NOT_NEEDED:
    class: SUPPLY_CRITICAL

INVENTORY_REQUEST:
  TABLEWARE:
    class: INVENTORY
  KNIVES_SPATULAS:
    class: INVENTORY
  PRICE_TAG_HOLDER:
    class: INVENTORY
  BAKING_EQUIPMENT:
    class: INVENTORY
  STAFF_EQUIPMENT:
    class: INVENTORY
  CLEANING_EQUIPMENT:
    class: INVENTORY
  EMPLOYEE_UNIFORM:
    class: INVENTORY

ON_CALL_SERVISE_REQUEST:
  FUNITURE_DRY_CLEANING:
    class: EXTERNAL_SERVICE
  PEST_CONTROL:
    class: EXTERNAL_SERVICE

MARKETING_REQUEST:
    REQUEST_MERCH:
      class: INVENTORY
    REQUEST_CURRENT_PROMOTION:
      class: MARKETING
    TV_ADVERTISING:
      class: MARKETING
    REMOVE_OUTDATED_ADVERTISING:
      class: MARKETING
    A3_MENU:
      class: MARKETING
    A4_MENU:
      class: MARKETING
    POSTERS:
      class: MARKETING

SECURITY_REQUEST:
  CAMERA_FOOTAGE_REQUEST:
    class: SECURITY_SERVICE
  CASH_COLLECTION_REQUEST:
    class: SECURITY_SERVICE
  BA0_SEAL_CHANGE_REQUEST:
    class: SECURITY_SERVICE

IT_REQUEST:
   POS_NOT_WORK:
     class: IT_SERVICE
   MONOBLOCK_NOT_WORK:
     class: IT_SERVICE
   POS_BAR_TABLET_NOT_WORK:
     class: IT_SERVICE
   OPTIONS_POS:
     class: IT_SERVICE
   CHANGE_PRISES:
     class: IT_SERVICE
   ADD_POSITION:
     class: IT_SERVICE
   DEL_POSITION:
     class: IT_SERVICE