CRITICAL_NOTIFICATION: "Важное оповещение"
CRITICAL_REQUEST: "Критическая заявка"
URGENT_REQUEST: 'Срочная заявка'
REGULAR_REQUEST: 'Обычная заявка'
SUPPLY_REQUEST: 'Заявка на поставку'
ALERT: 'Уведомление'
SECURITY_INCIDENT: 'Инцидент безопасности'
critical: 'Критический'
high: 'Высокий'
medium: 'Средний'
low: 'Низкий'
bar: 'Бар'
sales: 'Витрины'
outdoor: 'Внешняя территория'
hall: 'Торговый зал'
technical_staff: 'Зона тех персонала'
staff: 'Зона сотрудников'
freezer_room: 'Морозилка'
restroom: 'Уборные'
PRODUCTION_CRITICAL: 'Критически важный объект'
PRODUCTION_IMPORTANT: 'Необходимый объект'
COMFORT: 'Обычный объект'
FULL_FAILURE: 'Полная неисправность'
PARTIAL_PROBLEM: 'Частичная неполадка'
MINOR_ISSUE: 'Незначительная проблема'
STORE_REQUEST: 'Заявка на склад'
INVENTORY_REQUEST: 'Заявка в отдел инвентаря'
ON_CALL_SERVISE_REQUEST: 'Внешние службы'
MARKETING_REQUEST: 'Заявки маркетинга'
SECURITY_REQUEST: 'Заявки СБ'
IT_REQUEST: 'Заявки IT'
SUPPLY_CRITICAL: 'Срочная заявка'
SUPPLY_REGULAR: 'Регулярная заявка'
INVENTORY: 'Отдел снабжения'
IT_SERVICE: 'IT и кассовые сервисы'
MARKETING: 'Отдел маркетинга'
SECURITY_SERVICE: 'Запросы в СБ'
EXTERNAL_SERVICE: 'Вызов внешнего подрядчика'
OUT_OF_STOCK: 'Полное отсутствие'
LOW_STOCK: 'Почти полное отсутствие необходимого'
REQUEST:  'Стандартная заявка'
INCIDENT: 'Происшествие'
CAMPAIGN_START: 'Старт акции'
CRITICAL_ALERTS: 'Критическое уведомление'
SECURITY_ALERTS: 'Предупреждение СБ'
HR_ALERTS: 'Предупреждение HR'
CASH_ALERTS: 'Предупреждение бухгалтеру'
SERVICE_ALERTS: 'Предупреждение сервис менеджеру'
CRIT_ALERT: 'Уведомление руководителю'
HIGH_ALERT: 'Уведомление управляющему'
SEC_ALERT: 'Предупреждение СБ'
HR_ALERT: 'Предупреждение HR'
CASH_ALERT: 'Предупреждение бухгалтеру'
SERVICE_ALERT: 'Предупреждение сервис менеджеру'
EMPLOYEE: 'Сотрудник'
MANAGER: 'Управляющий'
SPECIALIST: 'Специалист'
OWNER: 'Руководитель'
HR: 'HR отдел'
SECURITY: 'Отдел безопасности'
ACCOUNTANT: 'Бухгалтерия'
ARS: 'ARS отдел'
IT: 'IT отдел'
STORE: 'Склад'
SERVICE: 'Сервис менеджер'
TOP_MANAGEMENT: 'Руководство'
BRANCH_MANAGER: 'Управляющий филиала'
LINE_STAFF: 'Сотрудник'
NEW: 'Создана'
CONFIRMED: 'Подтверждена'
IN_PROGRESS: "В работе"
WAITING_EXTERNAL: "Ожидание необходимого"
RESOLVED: 'Выполнена'
CLOSED: "Закрыта"
CANCELLED: "Отклонена"
ticket_id: "Заявка №"
creator_name: "Создал: "
branch_name: 'Филиал: '
'problem_name': "Проблема: "
'problem_type': 'Тип проблемы: '
zone: 'Зона: '
target: "Отдел: "
date_create: 'Созданa: '
sla_reaction_deadline: 'Время на реакцию: '
sla_resolution_deadline: 'Время на исполнение: '
current_state: "Текущий статус: "
date_close: "Дата закрытия: "
assigned_to: "Исполнитель: "
reject_comment: "Причина отмены: "
comment: 'Комментарий:'
priority: 'Приоритет: '
COFFEE_MACHINE: 'Кофемашина'
COFFEE_GRINDER: 'Кофемолка'
ICE_MAKER: 'Лёдогенератор'
REFRIGERATOR: 'Холодильник'
FREEZER: 'Морозильная камера'
ICE_CRUSH: 'Измельчитель льда'
JUICER: 'Соковыжималка'
BLENDER: 'Блендер'
BOILER: 'Бойлер'
TV: 'Телевизор'
LIGHTING: 'Освещение'
FAUCET: 'Кран'
PIPES: 'Трубы'
SOCKET: 'Розетки/проводка'
WATER_FILTER: 'Фильтр для воды'
OTHER: 'Другое'
MICROWAVE: 'Микроволновка'
BACE_OVEN: 'Печь для выпечки'
DRY_SHOWCASE: 'Сухая витрина'
COLD_SHOWCASE: 'Холодная витрина'
SHOWCASE_REFRIGERATOR: 'Витринный холодильник'
DOOR_FRIDGE: 'Дверной холодильник'
SHELF: 'Полка'
SIGNBOARD: 'Вывеска'
OUTDOOR_FURNITURE: 'Уличная мебель'
CANOPY: 'Навес'
FRONT_DOOR: 'Входная дверь'
FURNITURE: 'Мебель'
AIR_CONDITIONER: 'Кондиционер'
HEATER: 'Обогреватель'
SINK: 'Раковина'
LOCKER: 'Шкафчики'
TOILET: 'Унитаз'
HAND_DRYER: 'Сушилка для рук'
SOAP_DISPENSER: 'Дозатор мыла'
PAPER_DISPENSER: 'Дозатор бумаги'
BAR_FRESH: 'Свежие товары для бара'
BAR_CONSUMABLES: 'Расходники для бара'
BAR_DRINKS_AND_COFFEE: 'Напитки и кофе для бара'
BAR_NOT_MILK_FAST: 'Закончилось молоко '
BAR_NOT_COFFEE_FAST: 'Закончилось кофе'
SALES_CONSUMABLES: 'Расходники для продажи'
SALES_CHEMICAL: 'Бытовая химия'
SALES_HOUSE_GOODS: 'Канцтовары'
SALES_NOT_NEEDED: 'Закончилась позиция'
TABLEWARE: 'Посуда для гостей'
KNIVES_SPATULAS: 'Приборы для гостей'
PRICE_TAG_HOLDER: 'Ценникодержатели'
BAKING_EQUIPMENT: 'Инвентарь для выпечки'
STAFF_EQUIPMENT: 'Инвентарь для персонала'
CLEANING_EQUIPMENT: 'Чистящее оборудование'
EMPLOYEE_UNIFORM: 'Униформа сотрудникам'
FUNITURE_DRY_CLEANING: 'Химчистка мебели'
PEST_CONTROL: 'Борьба с вредителями'
REQUEST_MERCH: 'Мерч товар'
REQUEST_CURRENT_PROMOTION: 'Материалы для акции'
TV_ADVERTISING: 'Реклама для ТВ'
REMOVE_OUTDATED_ADVERTISING: 'Удалить старую рекламу'
A3_MENU: 'А3 меню'
A4_MENU: 'А4 меню'
POSTERS: 'Плакаты'
CAMERA_FOOTAGE_REQUEST: 'Запрос на камеры'
CASH_COLLECTION_REQUEST: 'Запрос на инкасацию'
BA0_SEAL_CHANGE_REQUEST: 'Мешки и печати для денег'
POS_NOT_WORK: 'Не работает POS'
MONOBLOCK_NOT_WORK: 'Не работает моноблок'
POS_BAR_TABLET_NOT_WORK: 'Не работает POS в баре'
OPTIONS_POS: 'Настройка POS'
CHANGE_PRISES: 'Изменить цены'
ADD_POSITION: 'Добавить позицию'
DEL_POSITION: 'Удалить позицию'
NO_ELECTRICITY: 'Нет света'
FULL_NO_WATER: 'Полностью нет воды'
NO_INTERNET: 'Нет интернета'
GOVERNMENT_INSPECTION: 'Проверка гос органов'
NO_COLD_OR_HOT_WATER: 'Частично нет воды'
THEFTS_ALERT: 'Предупреждение о краже'
AGGRESSIONS_ALERT: 'Предупреждение о агрессии'
ALARM_ALERT: 'Предупреждение о сигнализации'
LOST_KEY_ALERT: 'Предупреждение о потери ключей'
STAFF_SHORTAGES: 'Не хватает персонала'
INTERN_DID_NOT_SHOW_UP: 'Не явился стажёр'
SCHEDULING_ISSUES: 'Проблемы с графиком'
TEAM_CONFLICT: 'Конфликт в команде'
RETURNS: 'Сообщение о возврате'
REPORTING_ERRORS: 'Сообщение о ошибке в отчетах'
CASH_DISCREPANCIES: 'Расхождение в кассе'
CUSTOMER_COMPLAINTS: 'Жалоба от гостя'
CONFLICT: 'Конфликт с гостем'
CONTACT: 'Просьба связаться'
user_id: 'Пользователь №: '
user_name: 'Имя'
api_user_id: "ТГ код: "
role_name: 'Роль: '
depart_name: "Отдел:"
branch_manager: "Администратор: "
